class Color(DefaultColor):

    USERNAME_FG = 15
    USERNAME_BG = 10
    USERNAME_ROOT_BG = 1

    HOSTNAME_FG = 0
    HOSTNAME_BG = 6

    HOME_SPECIAL_DISPLAY = True
    HOME_FG = 12
    HOME_BG = 9
    PATH_FG = 12
    PATH_BG = 9
    CWD_FG = 7
    SEPARATOR_FG = 8

    READONLY_BG = 1
    READONLY_FG = 15

    REPO_CLEAN_FG = 2
    REPO_CLEAN_BG = 8
    REPO_DIRTY_FG = 3
    REPO_DIRTY_BG = 8

    JOBS_FG = 11
    JOBS_BG = 8

    CMD_PASSED_FG = 7
    CMD_PASSED_BG = 0
    CMD_FAILED_FG = 1
    CMD_FAILED_BG = 0

    SVN_CHANGES_FG = REPO_DIRTY_FG
    SVN_CHANGES_BG = REPO_DIRTY_BG

    VIRTUAL_ENV_BG = 15
    VIRTUAL_ENV_FG = 2
