class Color(DefaultColor):

    SOLARIZED_0 = 8
    SOLARIZED_1 = 0
    GREEN = 2
    BLUE = 4
    RED = 1
    CYAN = 6
    PINK = 5
    YELLOW = 3
    WHITE = 7
    GREY_0 = 10
    GREY_1 = 11
    GREY_2 = 12
    GREY_3 = 14
    ORANGE = 9
    PURPLE = 13
    WHITE_2 = 15

    USERNAME_FG = WHITE_2
    USERNAME_BG = GREY_1
    USERNAME_ROOT_BG = RED

    HOSTNAME_FG = WHITE
    HOSTNAME_BG = PURPLE

    HOME_SPECIAL_DISPLAY = True
    HOME_FG = WHITE
    HOME_BG = GREY_2
    PATH_FG = WHITE
    PATH_BG = GREY_3
    CWD_FG = WHITE
    SEPARATOR_FG = GREY_2

    READONLY_BG = RED
    READONLY_FG = WHITE

    REPO_CLEAN_FG = GREEN
    REPO_CLEAN_BG = WHITE
    REPO_DIRTY_FG = YELLOW
    REPO_DIRTY_BG = WHITE

    JOBS_FG = 4
    JOBS_BG = 8

    CMD_PASSED_FG = GREY_3
    CMD_PASSED_BG = WHITE
    CMD_FAILED_FG = WHITE_2
    CMD_FAILED_BG = RED

    SVN_CHANGES_FG = REPO_DIRTY_FG
    SVN_CHANGES_BG = REPO_DIRTY_BG

    VIRTUAL_ENV_BG = 15
    VIRTUAL_ENV_FG = 2
