
source ~/.vimrc-main

set background=dark
set t_Co=256
"let base16colorspace=256
colorscheme base16-ocean

" highlight group for "nbsp", "tab", and "trail"
hi SpecialKey ctermfg=DarkRed

" highlight group for "eol", "extends", and "precedes"
hi NonText cterm=none ctermfg=15

hi CursorLine ctermbg=8

hi Normal                 ctermfg=7   ctermbg=0
hi Special                ctermfg=14
"hi ColorColumn                        ctermbg=0
hi SpecialKey             ctermfg=6
hi NonText                ctermfg=6               term=none
hi CursorLine                         ctermbg=234
hi LineNr                 ctermfg=240 ctermbg=0   term=none
hi GitGutterAdd           ctermfg=2   ctermbg=0
hi GitGutterChange        ctermfg=3   ctermbg=0
hi GitGutterDelete        ctermfg=1   ctermbg=0
hi GitGutterChangeDelete  ctermfg=9   ctermbg=0
hi MatchParen             ctermfg=5
hi Comment                ctermfg=8
"hi String                 ctermfg=10
hi ErrorMsg               ctermfg=7 ctermbg=1
hi Todo                   ctermfg=7 ctermbg=5
hi Operator               ctermfg=3
hi javaScriptBraces       ctermfg=3
hi javaScriptIdentifier   ctermfg=12              cterm=bold
hi javaScriptFuncKeyword  ctermfg=1
hi javaScriptConditional  ctermfg=1

