
source ~/.vimrc-main

let g:airline_theme='sol'

set background=light
set t_Co=256
"let base16colorspace=256
colorscheme base16-ocean

hi Normal                             ctermbg=7
hi ColorColumn                        ctermbg=15
hi SpecialKey             ctermfg=6
hi NonText                ctermfg=6               term=none
hi CursorLine                         ctermbg=6
hi CursorLineNr           ctermfg=10
hi LineNr                 ctermfg=12  ctermbg=6   term=none
hi GitGutterAdd           ctermfg=10  ctermbg=6
hi GitGutterChange        ctermfg=11  ctermbg=6
hi GitGutterDelete        ctermfg=1   ctermbg=6
hi GitGutterChangeDelete  ctermfg=9   ctermbg=6
